"use client";

import React, { useState } from "react";
import { ChevronDown, HelpCircle } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

const faqs = [
  {
    question: "Do I still need an FSSAI license?",
    answer:
      "Yes. SuprSKU helps you generate the compliant labeling for your products, but you must still possess a valid FSSAI registration or license to manufacture or sell food in India.",
  },
  {
    question: "Is the generation engine legally valid?",
    answer:
      "Absolutely. Our engine is built strictly upon the FSSAI Food Safety and Standards (Labelling and Display) Regulations. We recommend a final review by your legal team for unique health claims or proprietary formulations.",
  },
  {
    question: "Can I use this for Amazon or Flipkart?",
    answer:
      "Yes! Labels generated by SuprSKU meet the strict photographic and regulatory requirements of major marketplaces like Amazon, Flipkart, Blinkit, and BigBasket.",
  },
  {
    question: "How does the AI handle ingredient RDA?",
    answer:
      "The system automatically calculates Recommended Dietary Allowance (RDA) percentages based on the age group and sex profiles defined in the latest FSSAI mandates, ensuring your nutritional table is 100% accurate.",
  },
];

const FAQ = () => {
  const [activeIdx, setActiveIdx] = useState<number | null>(null);

  return (
    <section id="faqs" className="py-32 bg-slate-950 px-6">
      <div className="max-w-3xl mx-auto space-y-16">
        <div className="text-center space-y-4">
           <div className="inline-flex items-center gap-2 text-emerald-400 font-bold uppercase tracking-[0.2em] text-xs font-headline">
              <HelpCircle size={16} /> Knowledge Base
           </div>
           <h2 className="text-4xl md:text-5xl font-extrabold text-white tracking-tight font-headline">
             Everything you <br className="md:hidden" /> need to know
           </h2>
        </div>

        <div className="space-y-4">
          {faqs.map((faq, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 10 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: idx * 0.1 }}
              className="glass-card rounded-2xl border border-white/5 overflow-hidden group"
            >
              <button
                onClick={() => setActiveIdx(activeIdx === idx ? null : idx)}
                className="flex justify-between items-center w-full p-8 font-bold text-left text-white/90 hover:text-white transition-colors group"
              >
                <span className="text-lg md:text-xl font-headline pr-8">{faq.question}</span>
                <motion.div
                  animate={{ rotate: activeIdx === idx ? 180 : 0 }}
                  transition={{ duration: 0.3, ease: "circOut" }}
                  className={`w-8 h-8 rounded-full flex items-center justify-center border transition-all ${
                     activeIdx === idx ? "bg-emerald-500 border-emerald-500 text-slate-950" : "bg-white/5 border-white/10 text-slate-400"
                  }`}
                >
                  <ChevronDown size={18} />
                </motion.div>
              </button>

              <AnimatePresence initial={false}>
                {activeIdx === idx && (
                  <motion.div
                    key="content"
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.4, ease: "easeInOut" }}
                    className="overflow-hidden"
                  >
                    <p className="px-8 pb-8 text-slate-400 text-lg leading-relaxed font-body border-t border-white/5 pt-6">
                      {faq.answer}
                    </p>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FAQ;
