"use client";

import React, { useState } from "react";
import { ChevronDown } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

const faqs = [
  {
    question: "Do I still need an FSSAI license?",
    answer:
      "Yes. SuprSKU helps you generate the compliant labeling for your products, but you must still possess a valid FSSAI registration or license to manufacture or sell food in India.",
  },
  {
    question: "Is this legally valid?",
    answer:
      "Absolutely. Our generation engine is built strictly upon the FSSAI Food Safety and Standards (Labelling and Display) Regulations. We recommend a final review by your legal team for unique health claims.",
  },
  {
    question: "Can I use this for Amazon/Flipkart?",
    answer:
      "Yes! Labels generated by SuprSKU meet the strict photographic requirements of major marketplaces like Amazon, Flipkart, Blinkit, and BigBasket.",
  },
];

const FAQ = () => {
  const [activeIdx, setActiveIdx] = useState<number | null>(null);

  return (
    <section id="faqs" className="py-24 max-w-3xl mx-auto px-6">
      <motion.h2
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.5 }}
        className="text-3xl font-extrabold text-center mb-12 text-on-surface font-headline"
      >
        Frequently Asked Questions
      </motion.h2>

      <div className="space-y-4">
        {faqs.map((faq, idx) => (
          <motion.div
            key={idx}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.4, delay: idx * 0.1 }}
            className="bg-white rounded-xl editorial-shadow border border-surface-container overflow-hidden"
          >
            <button
              onClick={() => setActiveIdx(activeIdx === idx ? null : idx)}
              className="flex justify-between items-center w-full p-6 font-bold text-left text-on-surface hover:text-primary transition-colors group"
            >
              <span className="font-headline">{faq.question}</span>
              <motion.span
                animate={{ rotate: activeIdx === idx ? 180 : 0 }}
                transition={{ duration: 0.25 }}
              >
                <ChevronDown className="text-on-surface-variant group-hover:text-primary transition-colors shrink-0" />
              </motion.span>
            </button>

            <AnimatePresence initial={false}>
              {activeIdx === idx && (
                <motion.div
                  key="content"
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: "auto", opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  transition={{ duration: 0.3, ease: "easeInOut" }}
                  className="overflow-hidden"
                >
                  <p className="px-6 pb-6 text-on-surface-variant text-sm leading-relaxed font-body border-t border-surface-container pt-4">
                    {faq.answer}
                  </p>
                </motion.div>
              )}
            </AnimatePresence>
          </motion.div>
        ))}
      </div>
    </section>
  );
};

export default FAQ;
