"use client";

import React from "react";
import Image from "next/image";
import { motion } from "framer-motion";
import { ShieldCheck, ArrowRight } from "lucide-react";

const Hero = () => {
  return (
    <section className="max-w-7xl mx-auto px-6 py-16 md:py-24 grid grid-cols-1 lg:grid-cols-12 gap-12 items-center overflow-hidden">
      <motion.div
        initial={{ opacity: 0, x: -20 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ duration: 0.6 }}
        className="lg:col-span-7 space-y-8"
      >
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-secondary-container text-on-secondary-container text-xs font-bold uppercase tracking-wider">
          <ShieldCheck size={16} />
          Trusted Compliance
        </div>
        <h1 className="text-5xl md:text-7xl font-extrabold tracking-tighter leading-[1.1] text-on-surface font-headline">
          Create your food label in <span className="text-primary italic">10 minutes</span>.
        </h1>
        <p className="text-lg md:text-xl text-on-surface-variant leading-relaxed max-w-2xl font-body">
          No confusion. No expensive consultants. Launch your D2C brand faster with a perfect, 100% FSSAI-compliant label generated by the SuprSKU wizard.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 pt-4">
          <a
            href="#waitlist"
            className="bg-primary-container text-on-primary-container px-8 py-4 rounded-xl text-lg font-bold editorial-shadow hover:brightness-105 active:scale-95 transition-all group font-headline text-center"
          >
            Join the Waitlist
            <ArrowRight className="inline-block ml-2 group-hover:translate-x-1 transition-transform" />
          </a>
          <button className="bg-white border border-outline-variant text-on-surface px-8 py-4 rounded-xl text-lg font-bold hover:bg-surface-container-low transition-all font-headline">
            Explore Solutions
          </button>
        </div>
      </motion.div>

      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.8, delay: 0.2 }}
        className="lg:col-span-5 relative"
      >
        <div className="relative rounded-2xl overflow-hidden editorial-shadow border border-white/40 aspect-[4/3]">
          <Image
            src="/hero-preview.png"
            alt="SuprSKU Dashboard - FSSAI Compliance Platform"
            fill
            sizes="(max-width: 768px) 100vw, 40vw"
            className="object-cover"
            priority
          />
          <div className="absolute inset-0 bg-gradient-to-t from-zinc-900/10 to-transparent" />
        </div>

        {/* Floating Trust Badge */}
        <motion.div
          initial={{ y: 20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ delay: 1, duration: 0.5 }}
          className="absolute -bottom-6 -left-6 bg-white p-4 rounded-xl shadow-xl flex items-center gap-3 border border-surface-container"
        >
          <div className="w-12 h-12 rounded-full bg-primary-fixed flex items-center justify-center">
            <ShieldCheck className="text-primary" />
          </div>
          <div>
            <p className="text-xs font-bold text-on-surface-variant uppercase tracking-widest font-headline">Compliance Score</p>
            <p className="text-lg font-extrabold text-primary font-headline">100% Guaranteed</p>
          </div>
        </motion.div>
      </motion.div>
    </section>
  );
};

export default Hero;
